### PR TITLE
Update dev vm to solr 8.9

### PR DESCRIPTION
**Pull request by lfarrell**
https://jira.lib.unc.edu/browse/HYC-1200
Depends on https://gitlab.lib.unc.edu/cdr/vagrant-rails/-/merge_requests/93

### CODE REVIEW

**Comment by bbpennel** [comment]
Would merging this branch break solr for environments outside of dev?

**Comment by lfarrell** [comment]
Unfortunately, yes. Our servers symlink to the solr/cofig directory.
```
lrwxrwxrwx 1 solr solr  36 Feb  1  2019 conf -> /net/deploy/ir/prod/hy-c/solr/config
```

**Comment by bbpennel** [comment]
Okay, so we shouldn't merge this until we can do the same update on the other servers.

**Comment by maxkadel** [comment]
Converting to draft to indicate that it shouldn't be merged until we get some system stuff figured out

**Comment by lfarrell** [comment]
Closing and reopening as new PR without all the commit history

**Pull request closed without merging**
