### PR TITLE
Migrate docker repo to @cazzerson on Docker Hub

### PR DESCRIPTION
**Pull request by cazzerson**
...while we find a more permanent home.

Two tests to confirm that this is working:

1)`docker compose pull` will try to pull from the repo under my account.
2) `docker compose build; docker compose push` will rebuild the containers and push them to the repo under my account. You will need to login with `docker login` first. @bbpennel @lfarrell @sharonluong should all have access.

### CODE REVIEW

**Review by bbpennel — APPROVED** [review]
This appears to work for me. Initially I got access denied when pushing the image, but after logging in via the docker desktop app I was about to push (I ended the push after about 10 minutes since it didn't seem productive)

**Review by sharonluong — APPROVED** [review]

**Comment by cazzerson** [comment]
Thanks! Could one of you please try to complete a push just to be sure that it works?

**Comment by bbpennel** [comment]
The upload kind of nukes my internet connection, making for bad zoom calls for everyone involved, but i could try to kick it off at the end of the night if we want to be sure it runs to completion (I stopped it at 30-40% I'm guessing)

**Comment by cazzerson** [comment]
Thanks, I appreciate that. I guess my fiber connection is paying off--it took me 2m13s to push a fresh build.

**Comment by sharonluong** [comment]
I tried it since I have fiber and it took a little less than two minutes to push.

**Comment by cazzerson** [comment]
Great, and I see it here: https://hub.docker.com/r/cazzerson/hy-c/tags

I'll consider this done!

**Pull request merged**
